### ISSUE TITLE
Insecure settings.py Configuration

### ISSUE THREAD

**Issue by Nonamaker** [jcari-dev/Item-Availlability-Checker-with-Email-Notification#1]
The `miniproject.settings.py` file has a couple potentially dangerous inclusions:
- Consider loading `SECRET_KEY` from an environment variable.
- `DEBUG = True` risky in production. Forcing an error returns debugging information that is potentially sensitive (i.e. database name, user, etc.) and could be used to craft a targeted attack.

**Comment by jcari-dev** [comment]
> The `miniproject.settings.py` file has a couple potentially dangerous inclusions:
> 
> * Consider loading `SECRET_KEY` from an environment variable.
> * `DEBUG = True` risky in production. Forcing an error returns debugging information that is potentially sensitive (i.e. database name, user, etc.) and could be used to craft a targeted attack.

Thank you! Both inclusions were addressed and the file was also removed from the commit history. While I knew about these vulnerabilities evidently I failed to address them.
